services:
  server:
    image: judge0/judge0:latest
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    logging:
      driver: none
    restart: always
    # command: sh -c "sudo apt-get update; sudo apt-get install -y python3-pip; pip3 install pandas; /api/scripts/server"
    command: sh -c "sudo apt-get update; sudo apt install -y python-pip; sudo apt-get install -y python3-pip; pip install pandas; pip3 install pandas; /api/scripts/server"

  worker:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    logging:
      driver: none
    restart: always

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    logging:
      driver: none
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    logging:
      driver: none
    restart: always

volumes:
  data: