services:
  server:
    image: judge0/judge0:latest
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    logging:
      driver: none
    restart: always

  worker:
    image: judge0/judge0:latest
    command: >
      sh -c "
        sudo wget https://www.python.org/ftp/python/3.8.1/Python-3.8.1.tgz &&
        sudo tar -xvf Python-3.8.1.tgz &&
        cd Python-3.8.1 &&
        ./configure --enable-optimizations &&
        make -j $(nproc) &&
        sudo make altinstall &&
        sudo apt-get update &&
        sudo apt-get install lsb-release &&
        sudo curl -O https://bootstrap.pypa.io/get-pip.py &&
        sudo python3.8 get-pip.py &&
        python3.8 -m pip install pandas &&
        cd .. &&
        ./scripts/workers
      "
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    logging:
      driver: none
    restart: always

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    logging:
      driver: none
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    logging:
      driver: none
    restart: always

volumes:
  data: